---
title: "R Code Cheat Sheet"
author: "STATS 250 Instructional Team"
date: "Last updated `r format(Sys.time(), '%d %B %Y')`" 
output: 
  html_document:
    toc: yes
    toc_float: yes
---

# External Resources

-   List of color names in R: <http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf>

# Assignment, Data Manipulation, General Syntax

## `<-`

-   Assigns a value to a name
-   `name <- value`

## `read.csv(file, stringsAsFactors = TRUE)`

-   `file` is the name of the file from which data are to be read
-   `stringsAsFactors` should generally be set to `TRUE` (all caps): this determines how text-like data in a CSV file is interpreted by R.

## `$`

-   what is a dollar sign really
-   `data_set_name$data_set_variable`

## `subset(data, subset)`

-   `data` is the name of the data.frame you want to make a subset of
-   `subset` is a logical expression indicating rows to keep. Remember to use "logical equals", `==` to test for equality; you can use regular comparison operators as well, like `>` for greater than, `<=` for less than or equal to, etc.

## `c(...)`
- `...` is a comma-separated list of objects to be combined into a vector. These can be numbers, text/"strings", etc., but they all need to be the same kind of thing.

### `~`
- Read as "by"
- Used in side-by-side boxplots, scatterplots, and finding linear models
- `y ~ x` is the correct syntax for linear; `numeric_variable ~` categorical_variable` is the correct syntax for side-by-side boxplots

# Data Previewing

## `head(x, n)`

-   `x` is a data.frame
-   `n` is the number of rows to print

## `str(object)`

-   `object` is the R object about which you want to have some information (i.e., see the `str`ucture of).

# Numerical Summaries

## `table(data_set_name$data_set_variable)`

-   creates a table of the frequencies of one categorical variable

## `table(data_set_name$data_set_variable, data_set_name$data_set_variable)`

-   creates a two way table of the frequencies of two categorical variables

## `summary(data_set_name$data_set_variable)`

-   creates the five number summary of a quantitative variable

## `cor(x, y)`
- Finds the correlation coefficient between the numeric variable *x* and the numeric variable *y*

## `cor(numeric_data_frame)`
- Prints a correlation matrix for a data frame with all numeric variables

# Graphical Summaries

## `barplot(table(data_set_name$data_set_variable))`

-   creates a barplot of a categorical variable

## `hist(data_set_name$data_set_variable, breaks)`

-   creates a histogram of a quantitative variable
-   `breaks` is the approximate number of breaks you want in the histogram (R will sometimes ignore this to make the plot prettier)

## `boxplot(x, ..., xlab, ylab, main, col)`

-   `x` is the data you want to create a boxplot of
-   `...` is additional data to include in the boxplot

## `plot(x, y, xlab, ylab, main, col)`

-   `x` is the variable you want to plot on the x axis
-   `y` is the variable you want to plot on the y axis

## `abline(linear_model_name)`
- Will plot the line found in `linear_model_name`

## Important plotting arguments

Note that since a table is not a plot, these arguments won't work in the `table()` function.

### `main = "Title of Your Graph in Double Quotes"`

-   graph title that must be inside a set of double quotes

### `xlab = "x-axis Label of Your Graph in Double Quotes"`

-   the x- (horizontal) axis label that must be inside a set of double quotes

### `ylab = "y-axis Label of Your Graph in Double Quotes"`

-   the y- (vertical) axis label that must be inside a set of double quotes

### `col = c("color1", ...)`

-   a *vector* of color names enclosed in the `c()` function; e.g., `col = c("red", "blue", "green")`.

# Linear Regression

## `lm(y ~ x, data = data_name)`
- Finds the linear model between *x* and *y* from `data_name`
- You'll want to assign this a name in order to use it later

## `summary(linear_model_name)`
- Prints relevant values of a linear model

# Simulation

## `rep(x, times)`
Makes a vector consisting of `x` copy/pasted `times` times

- `x` is the thing you want `rep`eated
- `times` is the number of times you want to `rep`eat `x`

## `set.seed(seed)`
Sets the "seed" of R's random number generator. After setting the seed, the sequence of random numbers R will produce is entirely determined/predictable. This is useful for ensuring you get the same results whenever you knit your code.

- `seed` is an integer. The seed you want to set.

## `sample(x, size, replace = FALSE)`
Takes a sample of the specified size from the elements of `x` using either with or without replacement.

- `x` is a vector of elements to sample from
- `size` is a non-negative integer giving the number of items to choose from `x`
- `replace` should be `TRUE` if you want to sample with replacement; defaults to `FALSE` to sample without replacement

## `replicate(n, expr)`
Runs the code in `expr` `n` times and reports the results. *NOT* the same as `rep()` - `replicate()` re-runs code; `rep()` copies and pastes the result of one run of the code.

- `n` is the number of times to run the code in `expr`
- `expr` is an "expression" -- basically a block of code contained in curly braces {} that you want to run `n` times.

## `shuffle_two_groups(data)`
Shuffles `data` for use in two-proportion simulations.
- *NOTE* this is not a standard R function and cannot be used without running `shuffle_two_groups.R` provided to you in relevant labs.


# Distributions

## Normal Distribution 

### `pnorm(q, mean = 0, sd = 1, lower.tail = TRUE)`
- `q` refers to the value you want to find the area above or below
  - `pnorm(q, 0, 1)` gives $P(Z < q)$ where $Z$ is $N(0,1)$
- `mean` refers to $\mu$, defaults to 0
- `sd` refers to $\sigma$, defaults to 1
- `lower.tail` controls which direction to "shade": `lower.tail = TRUE` goes less than `q`, `lower.tail = FALSE` goes greater than `q`; defaults to `TRUE`

### `qnorm(p, mean = 0, sd = 1, lower.tail = TRUE)`
- `p` refers to the area under the curve
  - `qnorm(p, 0, 1)` is the number such that the area to the left of it is `p`
- `mean` refers to $\mu$, defaults to 0
- `sd` refers to $\sigma$, defaults to 1
- `lower.tail` controls which direction to "shade": `lower.tail = TRUE` goes less than `q`, `lower.tail = FALSE` goes greater than `q`; defaults to `TRUE`

### `plot_norm(mean = 0, sd = 1, shadeValues, direction, col.shade, ...)`
- `mean` refers to $\mu$, defaults to 0
- `sd` refers to $\sigma$, defaults to 1
- `shadeValues` is a vector of up to 2 numbers that define the region you want to shade
- `direction` can be one of `less`, `greater`, `between`, or `beyond`, and controls the direction of shading between `shadeValues`. Must be `less` or `greater` if `shadeValues` has only one element; `between` or `beyond` if two
- `col.shade` controls the color of the shaded region, defaults to `"cornflowerblue"`
- `...` lets you specify other graphical parameters to control the appearance of the normal curve (e.g., `lwd`, `lty`, `col`, etc.)
- *NOTE* this is not a standard R function and cannot be used without running `plot_norm.R` provided to you in relevant labs.
